// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package validation

import (
	validator "github.com/go-playground/validator/v10"
	mock "github.com/stretchr/testify/mock"
)

// MockValidateOption is an autogenerated mock type for the ValidateOption type
type MockValidateOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: validate
func (_m *MockValidateOption) Execute(validate *validator.Validate) {
	_m.Called(validate)
}
